#!/bin/sh

rm ./app/+home/home-main.component.spec.js
rm ./app/+home/home-main.component.js
rm ./app/+home/home-sidenav.component.js
rm ./app/+home/home.e2e.js
rm ./app/+home/home.module.js
rm ./app/+home/home.routes.js
rm ./app/+home/index.js
rm ./app/+home/ng-zone-demo/index.js
rm ./app/+home/ng-zone-demo/ng-zone-demo.component.js
rm ./app/+home/responsive-home.component.js
rm ./app/+home/title/index.js
rm ./app/+home/title/title.service.spec.js
rm ./app/+home/title/title.service.js
rm ./app/+home/x-large/index.js
rm ./app/+home/x-large/x-large.directive.spec.js
rm ./app/+home/x-large/x-large.directive.js
rm ./app/+lobby/auto-paint-card.component.js
rm ./app/+lobby/index.js
rm ./app/+lobby/lobby.component.js
rm ./app/+lobby/lobby.module.js
rm ./app/+lobby/word-paint.component.js
rm ./app/+lobby/word-paint.datamodel.js
rm ./app/+lobby/word-paint.service.js
rm ./app/+peernet/gossipmonger.d.js
rm ./app/+peernet/index.js
rm ./app/+peernet/peer-connect.service.js
rm ./app/+peernet/peernet.module.js
rm ./app/+peernet/peerstuff.js
rm ./app/+peernet/seed-connect.resolver.js
rm ./app/+peernet/seed.component.js
rm ./app/app-root/app-root.component.js
rm ./app/app-root/app.e2e.js
rm ./app/app-root/floating-actions.component.js
rm ./app/app-root/global-navbar.component.js
rm ./app/app-root/index.js
rm ./app/app-root/inner-navbar.component.js
rm ./app/app-root/navballs.directive.js
rm ./app/app-root/navbar-data.datamodel.js
rm ./app/app-root/navbar-data.resolver.js
rm ./app/app-root/navbar-data.service.js
rm ./app/app-root/sidenav-action.service.js
rm ./app/app-root/top-toolbar.component.js
rm ./app/app.module.js
rm ./app/authentication/google-login.component.js
rm ./app/authentication/index.js
rm ./app/authentication/login-modal.component.js
rm ./app/authentication/passport.component.js
rm ./app/authentication/redirecting-error-handler.service.js
rm ./app/ballots/campaign-model.datamodel.js
rm ./app/digital-timer/clock-tick.datamodel.js
rm ./app/digital-timer/create-timer.service.js
rm ./app/digital-timer/digital-timer.component.js
rm ./app/environment.js
rm ./app/index.js
rm ./app/no-content/index.js
rm ./app/no-content/no-content.component.js
rm ./app/pool/image-chain-cache.service.js
rm ./app/pool/image-chain-def.datamodel.js
rm ./app/pool/image-lobby-action.component.js
rm ./app/pool/image-lobby-side.component.js
rm ./app/pool/image-lobby.component.js
rm ./app/pool/image-sequence-cache.service.js
rm ./app/pool/image-store.service.js
rm ./app/pool/index.js
rm ./app/pool/keys/keys.dictionary.js
rm ./app/pool/local-image.datamodel.js
rm ./app/pool/modal-image-chain-selection.service.js
rm ./app/pool/new-pool-modal.component.js
rm ./app/pool/point-mapping-config.service.js
rm ./app/pool/point-mapping.service.js
rm ./app/pool/pool-list-settings.datamodel.js
rm ./app/pool/pool-list.component.js
rm ./app/pool/pool-store.service.js
rm ./app/pool/pool.module.js
rm ./app/pool/resource-path-pool.resolver.js
rm ./app/pool/word-paint-input.datamodel.js
rm ./app/pool/word-paint-progress.datamodel.js
rm ./app/pool/word-paint-queue.service.js
rm ./app/pool/word-paint-result.datamodel.js
rm ./app/pool/word-paint-task.class.js
rm ./app/pool/word-paint-user-settings.service.js
rm ./app/scrolltest/index.js
rm ./app/scrolltest/scroll-action.component.js
rm ./app/scrolltest/scroll-main.component.js
rm ./app/scrolltest/scroll-side.component.js
rm ./app/scrolltest/scroll.module.js
rm ./app/shared/base-url.values.js
rm ./app/shared/blank-area/flex-spacer.directive.js
rm ./app/shared/blank-area/index.js
rm ./app/shared/canvas-cache/canvas-cache.module.js
rm ./app/shared/canvas-cache/durable-canvas-container.component.js
rm ./app/shared/canvas-cache/durable-canvas-ref.datamodel.js
rm ./app/shared/canvas-cache/durable-canvas.component.js
rm ./app/shared/canvas-cache/durable-canvas.service.js
rm ./app/shared/canvas-cache/index.js
rm ./app/shared/canvas-cache/source-from.directive.js
rm ./app/shared/canvas-util/canvas-access.directive.js
rm ./app/shared/canvas-util/dynamic-canvas-rendering-context-2d.class.js
rm ./app/shared/canvas-util/index.js
rm ./app/shared/canvas-util/paintable.directive.js
rm ./app/shared/canvas-util/point.datamodel.js
rm ./app/shared/component-util/abstract-selection.service.js
rm ./app/shared/component-util/can-activate.guard.js
rm ./app/shared/component-util/global-selection.service.js
rm ./app/shared/component-util/index.js
rm ./app/shared/index.js
rm ./app/shared/keys/keys.dictionary.js
rm ./app/shared/phrase-generator/index.js
rm ./app/shared/phrase-generator/new-named-canvas-modal.component.js
rm ./app/shared/phrase-generator/phrase-generator.service.js
rm ./app/shared/sdk/index.js
rm ./app/shared/sdk/lb.config.js
rm ./app/shared/sdk/models/Artwork.js
rm ./app/shared/sdk/models/BaseModels.js
rm ./app/shared/sdk/models/Container.js
rm ./app/shared/sdk/models/Email.js
rm ./app/shared/sdk/models/FireLoop.js
rm ./app/shared/sdk/models/FireLoopRef.js
rm ./app/shared/sdk/models/ImageChain.js
rm ./app/shared/sdk/models/index.js
rm ./app/shared/sdk/models/PeerConnection.js
rm ./app/shared/sdk/models/Pool.js
rm ./app/shared/sdk/models/StormpathUser.js
rm ./app/shared/sdk/models/User.js
rm ./app/shared/sdk/services/core/auth.service.js
rm ./app/shared/sdk/services/core/base.service.js
rm ./app/shared/sdk/services/core/error.service.js
rm ./app/shared/sdk/services/core/index.js
rm ./app/shared/sdk/services/core/io.service.js
rm ./app/shared/sdk/services/core/real.time.js
rm ./app/shared/sdk/services/core/search.params.js
rm ./app/shared/sdk/services/custom/Artwork.js
rm ./app/shared/sdk/services/custom/Container.js
rm ./app/shared/sdk/services/custom/Email.js
rm ./app/shared/sdk/services/custom/ImageChain.js
rm ./app/shared/sdk/services/custom/index.js
rm ./app/shared/sdk/services/custom/logger.service.js
rm ./app/shared/sdk/services/custom/PeerConnection.js
rm ./app/shared/sdk/services/custom/Pool.js
rm ./app/shared/sdk/services/custom/SDKModels.js
rm ./app/shared/sdk/services/custom/StormpathUser.js
rm ./app/shared/sdk/services/custom/User.js
rm ./app/shared/sdk/services/index.js
rm ./app/shared/sdk/sockets/socket.browser.js
rm ./app/shared/sdk/sockets/socket.connections.js
rm ./app/shared/sdk/sockets/socket.driver.js
rm ./app/shared/sdk/storage/cookie.browser.js
rm ./app/shared/sdk/storage/storage.browser.js
rm ./app/shared/sdk/storage/storage.swaps.js
rm ./app/shared/service-util/abstract-queue.service.js
rm ./app/shared/service-util/index.js
rm ./app/shared/service-util/match-media.service.js
rm ./app/shared/service-util/real-time-manager.service.js
rm ./app/shared/service-util/service-lifecycle.datamodel.js
rm ./app/shared/service-util/task-lifecycle.datamodel.js
rm ./app/stream-play/all-pixels.component.js
rm ./app/stream-play/all-points.component.js
rm ./app/stream-play/canvas-data.datamodel.js
rm ./app/stream-play/index.js
rm ./app/stream-play/paintable-point.pipe.js
rm ./app/stream-play/point-map.pipe.js
rm ./app/stream-play/point-stream.service.js
rm ./app/stream-play/point.datamodel.js
rm ./app/token-check-xhr-backend.service.js
rm ./custom-typings.d.js
rm ./main.browser.js
rm ./polyfills.browser.js
rm ./vendor.browser.js
